// @flow

// минимальная длина телефона (с учетом минимально возможной)
export const MIN_PHONE_LENGHT = 10;

// если телефон не распознан – по дефолту ставим россию, и разрешаем
// вводить дофига символов
export const DEFAULT_PROPS: {
  textСode: ICountryCode;
  numberCode: string;
  mask: string;
} = {
  textСode: 'ru',
  numberCode: '',
  mask: '### ### ### ## ## ##',
};

export type ICountryData = {placeholder: string; defaultCode: string};
export type ICountryCode = 'ru' | 'kz' | 'by' | 'ua';

// страны присутствия
export const BASE_COUNTRIES: Record<ICountryCode, ICountryData> = {
  ru: {placeholder: '7 123 456 78-90', defaultCode: '7'},
  kz: {placeholder: '7 123-456-78-90', defaultCode: '7'},
  by: {placeholder: '375 12 345-67-89', defaultCode: '375'},
  ua: {placeholder: '380 12 345-67-89', defaultCode: '380'},
};

export const rawCountries = [
  {
    textСode: 'ru',
    numberCode: '7',
    mask: '# ### ###-##-##',
    subCodes: ['9'],
  },
  {
    textСode: 'kz',
    numberCode: '7',
    mask: '# ###-###-##-##',
    subCodes: [
      '7',
      '310',
      '311',
      '312',
      '313',
      '315',
      '318',
      '321',
      '324',
      '325',
      '326',
      '327',
      '336',
    ],
  },
  {
    textСode: 'by',
    numberCode: '375',
    mask: '### ## ###-##-##',
    subCodes: [],
  },
  {
    textСode: 'ua',
    numberCode: '380',
    mask: '### ## ###-##-##',
    subCodes: [],
  },
  {
    textСode: 'af',
    numberCode: '93',
    mask: '## ## ###-####',
    subCodes: [],
  },
  {
    textСode: 'al',
    numberCode: '355',
    mask: '### # ###-####',
    subCodes: [],
  },
  {
    textСode: 'ad',
    numberCode: '376',
    mask: '### ###-###',
    subCodes: [],
  },
  {
    textСode: 'ar',
    numberCode: '54',
    mask: '## ## ####-####',
    subCodes: [],
  },
  {
    textСode: 'am',
    numberCode: '374',
    mask: '### ## ######',
    subCodes: [],
  },
  {
    textСode: 'aw',
    numberCode: '297',
    mask: '### ### ####',
    subCodes: [],
  },
  {
    textСode: 'au',
    numberCode: '61',
    mask: '## # #### ####',
    subCodes: ['2', '3', '4', '7', '8', '02', '03', '04', '07', '08'],
  },
  {
    textСode: 'at',
    numberCode: '43',
    mask: '## # ##########',
    subCodes: [],
  },
  {
    textСode: 'az',
    numberCode: '994',
    mask: '### ## ### ##-##',
    subCodes: [],
  },
  {
    textСode: 'bs',
    numberCode: '1242',
    mask: '# ###-###-####',
    subCodes: [],
  },
  {
    textСode: 'bh',
    numberCode: '973',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'bd',
    numberCode: '880',
    mask: '### #-#######',
    subCodes: [],
  },
  {
    textСode: 'bb',
    numberCode: '1246',
    mask: '# ###-###-####',
    subCodes: [],
  },

  {
    textСode: 'be',
    numberCode: '32',
    mask: '## # ### ## ##',
    subCodes: [],
  },
  {
    textСode: 'bz',
    numberCode: '501',
    mask: '### ###-####',
    subCodes: [],
  },
  {
    textСode: 'bo',
    numberCode: '591',
    mask: '### #######',
    subCodes: [],
  },
  {
    textСode: 'ba',
    numberCode: '387',
    mask: '### ## ###-###',
    subCodes: [],
  },
  {
    textСode: 'br',
    numberCode: '55',
    mask: '## ## ####-####',
    subCodes: [],
  },
  {
    textСode: 'bn',
    numberCode: '673',
    mask: '### ### ####',
    subCodes: [],
  },
  {
    textСode: 'bg',
    numberCode: '359',
    mask: '### # ### ####',
    subCodes: [],
  },
  {
    textСode: 'kh',
    numberCode: '855',
    mask: '### ## ### ###',
    subCodes: [],
  },
  {
    textСode: 'ca',
    numberCode: '1',
    mask: '# ###-###-####',
    subCodes: [
      '204',
      '226',
      '236',
      '249',
      '250',
      '289',
      '306',
      '343',
      '365',
      '367',
      '387',
      '403',
      '416',
      '418',
      '431',
      '437',
      '438',
      '450',
      '506',
      '514',
      '519',
      '548',
      '579',
      '581',
      '587',
      '604',
      '613',
      '639',
      '647',
      '672',
      '705',
      '709',
      '742',
      '778',
      '780',
      '782',
      '807',
      '819',
      '825',
      '867',
      '873',
      '902',
      '905',
    ],
  },
  {
    textСode: 'cl',
    numberCode: '56',
    mask: '## # #### ####',
    subCodes: [],
  },
  {
    textСode: 'cn',
    numberCode: '86',
    mask: '## ## #####',
    subCodes: [],
  },
  {
    textСode: 'co',
    numberCode: '57',
    mask: '## # #######',
    subCodes: [],
  },
  {
    textСode: 'hr',
    numberCode: '385',
    mask: '### # #### ###',
    subCodes: [],
  },
  {
    textСode: 'cu',
    numberCode: '53',
    mask: '## # #######',
    subCodes: [],
  },
  {
    textСode: 'cy',
    numberCode: '357',
    mask: '### ## ######',
    subCodes: [],
  },
  {
    textСode: 'cz',
    numberCode: '420',
    mask: '### ### ### ###',
    subCodes: [],
  },
  {
    textСode: 'dk',
    numberCode: '45',
    mask: '## ## ## ## ##',
    subCodes: [],
  },
  {
    textСode: 'dm',
    numberCode: '1767',
    mask: '# ###-###-####',
    subCodes: [],
  },
  {
    textСode: 'do',
    numberCode: '1',
    mask: '# ###-###-####',
    subCodes: ['809', '829', '849'],
  },
  {
    textСode: 'ec',
    numberCode: '593',
    mask: '### ## ### ####',
    subCodes: [],
  },
  {
    textСode: 'eg',
    numberCode: '20',
    mask: '## # ########',
    subCodes: [],
  },
  {
    textСode: 'sv',
    numberCode: '503',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'ee',
    numberCode: '372',
    mask: '### ## ######',
    subCodes: [],
  },
  {
    textСode: 'fj',
    numberCode: '679',
    mask: '### ### ####',
    subCodes: [],
  },
  {
    textСode: 'fi',
    numberCode: '358',
    mask: '### ### #####',
    subCodes: [],
  },
  {
    textСode: 'fr',
    numberCode: '33',
    mask: '## # ## ## ## ##',
    subCodes: [],
  },
  {
    textСode: 'gf',
    numberCode: '594',
    mask: '### ### ## ## ##',
    subCodes: [],
  },
  {
    textСode: 'pf',
    numberCode: '689',
    mask: '### ## ## ## ##',
    subCodes: [],
  },
  {
    textСode: 'ge',
    numberCode: '995',
    mask: '### ## ### ## ##',
    subCodes: [],
  },
  {
    textСode: 'de',
    numberCode: '49',
    mask: '## ### # #######',
    subCodes: [],
  },
  {
    textСode: 'gr',
    numberCode: '30',
    mask: '## ## #### ####',
    subCodes: [],
  },
  {
    textСode: 'gd',
    numberCode: '1473',
    mask: '# ###-###-####',
    subCodes: [],
  },

  {
    textСode: 'gp',
    numberCode: '590',
    mask: '### ### ## ## ##',
    subCodes: [],
  },
  {
    textСode: 'gu',
    numberCode: '1671',
    mask: '# ###-###-####',
    subCodes: [],
  },
  {
    textСode: 'gt',
    numberCode: '502',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'ht',
    numberCode: '509',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'hn',
    numberCode: '504',
    mask: '### ####-####',
    subCodes: [],
  },
  {
    textСode: 'hk',
    numberCode: '852',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'hu',
    numberCode: '36',
    mask: '## ## ### ####',
    subCodes: [],
  },
  {
    textСode: 'is',
    numberCode: '354',
    mask: '### ### ####',
    subCodes: [],
  },
  {
    textСode: 'in',
    numberCode: '91',
    mask: '## ### ### ####',
    subCodes: [],
  },
  {
    textСode: 'id',
    numberCode: '62',
    mask: '## ### #######',
    subCodes: [],
  },
  {
    textСode: 'ir',
    numberCode: '98',
    mask: '## ##########',
    subCodes: [],
  },
  {
    textСode: 'iq',
    numberCode: '964',
    mask: '### ### ### ####',
    subCodes: [],
  },
  {
    textСode: 'ie',
    numberCode: '353',
    mask: '### ## ### ###',
    subCodes: [],
  },
  {
    textСode: 'il',
    numberCode: '972',
    mask: '### #-###-#####',
    subCodes: [],
  },
  {
    textСode: 'it',
    numberCode: '39',
    mask: '## ## ########',
    subCodes: [],
  },
  {
    textСode: 'jm',
    numberCode: '1876',
    mask: '# ###-###-####',
    subCodes: [],
  },
  {
    textСode: 'jp',
    numberCode: '81',
    mask: '## ###-##-####',
    subCodes: [],
  },
  {
    textСode: 'jo',
    numberCode: '962',
    mask: '### # ### ####',
    subCodes: [],
  },
  {
    textСode: 'xk',
    numberCode: '383',
    mask: '### ## ##########',
    subCodes: [],
  },
  {
    textСode: 'kw',
    numberCode: '965',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'kg',
    numberCode: '996',
    mask: '### ### ### ###',
    subCodes: [],
  },
  {
    textСode: 'la',
    numberCode: '856',
    mask: '### ## ## ### ###',
    subCodes: [],
  },
  {
    textСode: 'lv',
    numberCode: '371',
    mask: '### ## ### ###',
    subCodes: [],
  },
  {
    textСode: 'lb',
    numberCode: '961',
    mask: '### # ### ###',
    subCodes: [],
  },
  {
    textСode: 'li',
    numberCode: '423',
    mask: '### ## ### ## ##',
    subCodes: [],
  },
  {
    textСode: 'lt',
    numberCode: '370',
    mask: '### ### #####',
    subCodes: [],
  },
  {
    textСode: 'lu',
    numberCode: '352',
    mask: '### ## ###',
    subCodes: [],
  },
  {
    textСode: 'mo',
    numberCode: '853',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'mk',
    numberCode: '389',
    mask: '### # ### ####',
    subCodes: [],
  },
  {
    textСode: 'my',
    numberCode: '60',
    mask: '## #-#### ####',
    subCodes: [],
  },

  {
    textСode: 'mv',
    numberCode: '960',
    mask: '### ###-####',
    subCodes: [],
  },
  {
    textСode: 'mt',
    numberCode: '356',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'mx',
    numberCode: '52',
    mask: '## ## #### ####',
    subCodes: ['55', '81', '33', '656', '664', '998', '774', '229'],
  },
  {
    textСode: 'md',
    numberCode: '373',
    mask: '### ## ### ###',
    subCodes: [],
  },
  {
    textСode: 'mn',
    numberCode: '976',
    mask: '### ## ## ####',
    subCodes: [],
  },
  {
    textСode: 'me',
    numberCode: '382',
    mask: '### ## ### ###',
    subCodes: [],
  },
  {
    textСode: 'mm',
    numberCode: '95',
    mask: '## # ### ###',
    subCodes: [],
  },
  {
    textСode: 'np',
    numberCode: '977',
    mask: '### #-#######',
    subCodes: [],
  },
  {
    textСode: 'nl',
    numberCode: '31',
    mask: '## ## ### ####',
    subCodes: [],
  },
  {
    textСode: 'nz',
    numberCode: '64',
    mask: '## #-### ####',
    subCodes: [],
  },
  {
    textСode: 'ni',
    numberCode: '505',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'no',
    numberCode: '47',
    mask: '## ## ## ## ##',
    subCodes: [],
  },
  {
    textСode: 'om',
    numberCode: '968',
    mask: '### ### #####',
    subCodes: [],
  },
  {
    textСode: 'pk',
    numberCode: '92',
    mask: '## ## ########',
    subCodes: [],
  },
  {
    textСode: 'ps',
    numberCode: '970',
    mask: '### #-###-####',
    subCodes: [],
  },
  {
    textСode: 'py',
    numberCode: '595',
    mask: '### ### #####',
    subCodes: [],
  },
  {
    textСode: 'pe',
    numberCode: '51',
    mask: '## ## ######',
    subCodes: [],
  },
  {
    textСode: 'ph',
    numberCode: '63',
    mask: '## # ### ####',
    subCodes: [],
  },
  {
    textСode: 'pl',
    numberCode: '48',
    mask: '## ## ### ## ##',
    subCodes: [],
  },
  {
    textСode: 'pt',
    numberCode: '351',
    mask: '### # #### ####',
    subCodes: [],
  },
  {
    textСode: 'pr',
    numberCode: '1',
    mask: '# ### ### ####',
    subCodes: ['787', '939'],
  },
  {
    textСode: 'qa',
    numberCode: '974',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'ro',
    numberCode: '40',
    mask: '## ## ### ####',
    subCodes: [],
  },
  {
    textСode: 'sm',
    numberCode: '378',
    mask: '### #### ######',
    subCodes: [],
  },
  {
    textСode: 'sa',
    numberCode: '966',
    mask: '### #### #####',
    subCodes: [],
  },
  {
    textСode: 'rs',
    numberCode: '381',
    mask: '### ## #######',
    subCodes: [],
  },
  {
    textСode: 'sg',
    numberCode: '65',
    mask: '## #### ####',
    subCodes: [],
  },
  {
    textСode: 'sk',
    numberCode: '421',
    mask: '### ##/### ## ##',
    subCodes: [],
  },
  {
    textСode: 'si',
    numberCode: '386',
    mask: '### # ### ## ##',
    subCodes: [],
  },
  {
    textСode: 'sb',
    numberCode: '677',
    mask: '### #####',
    subCodes: [],
  },
  {
    textСode: 'kr',
    numberCode: '82',
    mask: '## ####-####',
    subCodes: [],
  },
  {
    textСode: 'es',
    numberCode: '34',
    mask: '## ### ## ## ##',
    subCodes: [],
  },
  {
    textСode: 'lk',
    numberCode: '94',
    mask: '## ### ### ###',
    subCodes: [],
  },
  {
    textСode: 'se',
    numberCode: '46',
    mask: '## ## ### ## ##',
    subCodes: [],
  },
  {
    textСode: 'ch',
    numberCode: '41',
    mask: '## ## ### ## ##',
    subCodes: [],
  },
  {
    textСode: 'sy',
    numberCode: '963',
    mask: '### ## ### ####',
    subCodes: [],
  },
  {
    textСode: 'tw',
    numberCode: '886',
    mask: '### # #### ####',
    subCodes: [],
  },
  {
    textСode: 'tj',
    numberCode: '992',
    mask: '### ### ## ####',
    subCodes: [],
  },
  {
    textСode: 'th',
    numberCode: '66',
    mask: '## # ### ####',
    subCodes: [],
  },
  {
    textСode: 'tr',
    numberCode: '90',
    mask: '## ### ### ## ##',
    subCodes: [],
  },
  {
    textСode: 'tm',
    numberCode: '993',
    mask: '### ## ######',
    subCodes: [],
  },
  {
    textСode: 'ae',
    numberCode: '971',
    mask: '### # ### ####',
    subCodes: [],
  },
  {
    textСode: 'gb',
    numberCode: '44',
    mask: '## ### ### ####',
    subCodes: [],
  },
  {
    textСode: 'us',
    numberCode: '1',
    mask: '# ###-###-####',
    subCodes: [
      '20',
      '210',
      '212',
      '213',
      '214',
      '215',
      '216',
      '217',
      '218',
      '219',
      '220',
      '223',
      '224',
      '225',
      '226',
      '228',
      '229',
      '231',
      '234',
      '236',
      '239',
      '240',
      '242',
      '246',
      '248',
      '250',
      '251',
      '252',
      '253',
      '254',
      '256',
      '260',
      '262',
      '264',
      '267',
      '268',
      '269',
      '270',
      '272',
      '276',
      '279',
      '281',
      '284',
      '289',
      '30',
      '310',
      '312',
      '31',
      '320',
      '321',
      '323',
      '325',
      '326',
      '330',
      '331',
      '332',
      '334',
      '336',
      '337',
      '339',
      '340',
      '341',
      '343',
      '345',
      '346',
      '347',
      '351',
      '352',
      '360',
      '361',
      '364',
      '365',
      '367',
      '380',
      '385',
      '386',
      '40',
      '410',
      '412',
      '413',
      '414',
      '415',
      '417',
      '418',
      '419',
      '423',
      '424',
      '425',
      '430',
      '431',
      '432',
      '434',
      '435',
      '437',
      '438',
      '440',
      '441',
      '442',
      '443',
      '445',
      '458',
      '463',
      '459',
      '470',
      '473',
      '475',
      '478',
      '479',
      '480',
      '50',
      '51',
      '520',
      '530',
      '531',
      '534',
      '539',
      '540',
      '541',
      '548',
      '551',
      '559',
      '561',
      '562',
      '563',
      '564',
      '567',
      '570',
      '573',
      '574',
      '575',
      '579',
      '580',
      '581',
      '585',
      '586',
      '587',
      '60',
      '610',
      '612',
      '614',
      '615',
      '616',
      '617',
      '618',
      '619',
      '620',
      '623',
      '626',
      '629',
      '630',
      '631',
      '636',
      '640',
      '641',
      '646',
      '650',
      '651',
      '657',
      '658',
      '659',
      '660',
      '661',
      '662',
      '664',
      '667',
      '670',
      '671',
      '673',
      '678',
      '680',
      '681',
      '682',
      '684',
      '689',
      '70',
      '712',
      '713',
      '714',
      '715',
      '716',
      '717',
      '718',
      '719',
      '720',
      '724',
      '725',
      '726',
      '727',
      '731',
      '732',
      '734',
      '737',
      '740',
      '743',
      '747',
      '754',
      '757',
      '758',
      '760',
      '762',
      '763',
      '765',
      '767',
      '769',
      '770',
      '772',
      '773',
      '774',
      '775',
      '778',
      '779',
      '781',
      '782',
      '784',
      '785',
      '786',
      '787',
      '80',
      '810',
      '812',
      '813',
      '814',
      '815',
      '816',
      '817',
      '818',
      '819',
      '820',
      '825',
      '828',
      '829',
      '830',
      '831',
      '832',
      '838',
      '839',
      '843',
      '845',
      '847',
      '848',
      '849',
      '850',
      '854',
      '856',
      '857',
      '858',
      '859',
      '860',
      '862',
      '863',
      '864',
      '865',
      '867',
      '868',
      '869',
      '870',
      '872',
      '873',
      '876',
      '878',
      '90',
      '910',
      '912',
      '913',
      '914',
      '915',
      '916',
      '918',
      '919',
      '920',
      '925',
      '928',
      '931',
      '934',
      '936',
      '937',
      '938',
      '940',
      '941',
      '947',
      '949',
      '951',
      '952',
      '954',
      '956',
      '959',
      '970',
      '971',
      '972',
      '973',
      '978',
      '979',
      '980',
      '985',
      '986',
      '989',
      '907',
    ],
  },
  {
    textСode: 'uy',
    numberCode: '598',
    mask: '### #### ####',
    subCodes: [],
  },
  {
    textСode: 'uz',
    numberCode: '998',
    mask: '### ## ### ## ##',
    subCodes: [],
  },
  {
    textСode: 've',
    numberCode: '58',
    mask: '## ###-#######',
    subCodes: [],
  },
  {
    textСode: 'vn',
    numberCode: '84',
    mask: '## ## #### ####',
    subCodes: [],
  },
];
