/**
 * Flowtype definitions for usePersistCallback.ts
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.13.0
 */

import { useEffect, useCallback, useRef } from "react";
import type { DependencyList } from "react";
declare export default function usePersistCallback<ARG, RET>(
  callback: (...args: ARG[]) => RET,
  deps: DependencyList | void
): (...args: ARG[]) => RET;
