/**
 * Flowtype definitions for index.tsx
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.13.0
 */

import React, { forwardRef } from "react";
import classnames from "classnames";
import styles from "./MenuItem.module.scss";
export type DropdownItemProps = {
  divided?: boolean,
  disabled?: boolean,
  to?: string,
  rounded?: boolean,
  current?: boolean,
  ...
} & React.AnchorHTMLAttributes<HTMLAnchorElement>;
declare var DropdownItem: React.ForwardRefExoticComponent<
  DropdownItemProps & React.RefAttributes<HTMLAnchorElement>
>;
declare export default typeof DropdownItem;
