/**
 * Flowtype definitions for index.tsx
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.13.0
 */

import React, { useCallback, useContext } from "react";
import type { ReactElement } from "react";
import { DropdownContext } from "components/Dropdown";
import styles from "./DropdownToggler.module.scss";
export interface DropdownTogglerProps {
  children: React.Node;
}
declare export default function DropdownToggler(
  x: DropdownTogglerProps
): ReactElement;
