import { forwardRef } from 'react';
import wrapControlWithRef from './wrapControlWithRef';
import BareInput from './BareInput';
import BareTextarea from './BareTextarea';
import BareInputUnit from './BareInputUnit';
import { default as FormControl } from './FormControl';
const Input = /*#__PURE__*/forwardRef(wrapControlWithRef(BareInput));
const InputUnit = /*#__PURE__*/forwardRef(wrapControlWithRef(BareInputUnit));
const Textarea = /*#__PURE__*/forwardRef(wrapControlWithRef(BareTextarea));
export { wrapControlWithRef, FormControl, Input, InputUnit, Textarea };