# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'Push/PR checks'

on: [pull_request]

jobs:
  test:
    name: test
    uses: EruditorGroup/profi-design-system/.github/workflows/test.yaml@master

  lint:
    name: lint
    uses: EruditorGroup/profi-design-system/.github/workflows/lint.yaml@master

  screenshot-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{hashFiles('yarn.lock')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - run: NODE_ENV=production yarn build

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Europe/Moscow'
          timezoneWindows: 'Moscow Standard Time'
          timezoneMacos: 'Europe/Moscow'
      - run: yarn test:storybook

      - name: Archive screenshot diffs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: image_snapshots_diff_output
          path: __image_snapshots__/__diff_output__
