# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'Push/PR checks'

on: [pull_request]

jobs:

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  build: 
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-
      - run: NODE_ENV=production yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            packages/*/lib
            packages/*/es

  jest:
    needs: 
      - dependencies
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: 'yarn'

      - run: yarn
      - run: yarn test

  lint:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: 'yarn'

      - run: yarn
      - run: yarn lint

  screenshot-testing:
    needs: 
      - dependencies
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build

      - uses: actions/setup-node@v1
        continue-on-error: true
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Europe/Moscow'
          timezoneWindows: 'Moscow Standard Time'
          timezoneMacos: 'Europe/Moscow'
      - run: yarn test:storybook

      - name: Archive screenshot diffs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: image_snapshots_diff_output
          path: __image_snapshots__/__diff_output__
