# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'Push/PR checks'

on: [pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint

  screenshot-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        continue-on-error: true
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
      - run: yarn test:storybook

      - name: Archive screenshot diffs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: image_snapshots_diff_output
          path: |
            __image_snapshots__/__diff_output__
            storybook-static
