# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'Push/PR checks'

on: [pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - run: yarn --frozen-lockfile
      - run: yarn build:cjs
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - run: yarn --frozen-lockfile
      - run: yarn lint

  screenshot-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        continue-on-error: true
        with:
          node-version: 14.15.0-alpine
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: NODE_ENV=production yarn build

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Europe/Moscow'
          timezoneWindows: 'Moscow Standard Time'
          timezoneMacos: 'Europe/Moscow'
      - run: yarn test:storybook

      - name: Archive screenshot diffs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: image_snapshots_diff_output
          path: __image_snapshots__/__diff_output__
