name: 'npm package: publish'
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint

  npm_package_publish:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build package
        run: |
          yarn
          yarn build
        env:
          NODE_ENV: production

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

      - name: Configure CI Git User
        run: |
          git config user.email "mischenkoav@profi.ru"
          git config user.name "Publisher"
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/EruditorGroup/profi-design-system
        env:
          GITHUB_PAT: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

      - name: Checkout and pull branch
        run: git checkout "${GITHUB_REF:11}" && git pull

      - name: Publish package
        run: lerna publish --conventional-commits --no-git-tag-version --yes
