name: 'npm package: publish'
on:
  release:
    types: [published]

jobs:
  dependencies: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: 'yarn'
      - run: yarn
      
    
  build: 
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: 'yarn'
      - run: yarn
      - run: NODE_ENV=production yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            packages/*/lib
            packages/*/es

  test:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: 'yarn'
      - run: yarn
      - run: yarn test

  lint:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: 'yarn'
      - run: yarn
      - run: yarn lint

  npm_package_publish:
    needs:
      - dependencies
      - build
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        with:
          name: build

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: 'yarn'
      - run: yarn

      - name: Configure CI Git User
        run: |
          git config user.name "GitHub"
          git config user.email "noreply@github.com"

      - name: Set .npmrc (publish token) and GIT_TAG env
        run: |
          printf "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n" > ~/.npmrc
          echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Create release branch & Publish package
        run: |
          git checkout -b release/${{ env.GIT_TAG }}
          git push --set-upstream origin release/${{ env.GIT_TAG }}
          yarn run publish

      - name: Create pull request
        id: create-pr
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "release/${{ env.GIT_TAG }}",
              base: "master",
              title: "chore: changelog ${{ env.GIT_TAG }}"
            })
