name: 'npm package: publish'
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint

  npm_package_publish:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      - run: git config user.email "mischenkoav@profi.ru"
      - run: git config user.name "Publisher"

      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
        env:
          NODE_ENV: production
      - run: git checkout master
      - run: git pull
      - run: lerna publish --conventional-commits --no-git-tag-version --yes
