name: 'npm package: publish'
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint

  npm_package_publish:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: NODE_ENV=production yarn build

      - name: Configure CI Git User
        run: |
          git config user.name "GitHub"
          git config user.email "noreply@github.com"

      - name: Create release branch
        id: branch_name
        run: |
          echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          git checkout -b release/${{ env.GIT_TAG }}
          git push --set-upstream origin release/${{ env.GIT_TAG }}

      - name: Set .npmrc (publish token)
        run: printf "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n" > ~/.npmrc

      - name: Publish package & create pull request
        run: |
          yarn run publish
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/pulls \
            -d '{"head":"release/${{ env.GIT_TAG }}","base":"master"}'
