name: 'npm package: publish'

on:
  create:
    tags:
      - '*'

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - name: Archive & upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules
            
  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with: 
          name: node_modules
      - run: yarn
      - run: yarn build
      - name: Archive & upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
            !dist/**/*.md

  test:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with: 
          name: node_modules
      - run: yarn
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with: 
          name: node_modules
      - run: yarn
      - run: yarn lint

  npm_package_publish:
    needs: 
      - test
      - lint
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with: 
          name: dist
      - run: printf "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n@profiru:registry=https://npm.pkg.github.com/" > ~/.npmrc
      - run: npm publish
