name: 'npm package: publish'
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint

  npm_package_publish:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: NODE_ENV=production yarn build

      - name: Configure CI Git User
        run: |
          git config user.email "mischenkoav@profi.ru"
          git config user.name "Publisher"
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/EruditorGroup/profi-design-system
        env:
          GITHUB_PAT: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

      - name: Fetch and checkout
        run: git fetch && git checkout yarn.lock && git checkout master # если на тег, то git checkout "${GITHUB_REF/refs\/tags\//}". Но ругается Detached git HEAD.

      - name: Set .npmrc (publish token)
        run: printf "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Publish package
        run: npm run publish
