name: 'npm package: publish'
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint

  npm_package_publish:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: NODE_ENV=production yarn build

      - name: Fetch & checkout
        id: branch_name
        run: |
          git fetch
          git checkout yarn.lock 
          git checkout master
          echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Set .npmrc (publish token)
        run: printf "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n" > ~/.npmrc

      - name: Create release branch & publish package
        run: |
          git checkout -b release/${{ env.GIT_TAG }}
          git push --set-upstream origin release/${{ env.GIT_TAG }}
          git branch
          yarn run publish --no-push
          git push --tags

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/${{ env.GIT_TAG }}
          base: master
          title: Release "${{ env.GIT_TAG }}" changes
          commit-message: Release "${{ env.GIT_TAG }}" changes
