name: 'storyshots'

on: workflow_dispatch

jobs:
  screenshot-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        continue-on-error: true
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: NODE_ENV=production yarn build

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Europe/Moscow'
          timezoneWindows: 'Moscow Standard Time'
          timezoneMacos: 'Europe/Moscow'

      - run: yarn build:storybook --quiet

      - name: Update snapshots
        env:
          MODULE_TYPE: cjs
        run: yarn jest --config=storyshots.config.js --updateSnapshot

      - name: Commit files
        run: |
          git config --global user.email "mischenkoav@eruditorgroup.com"
          git config --global user.name "mischenkoav"
          git commit -m "fix(storyshots): update" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github-token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
