name: 'storyshots'

on: workflow_dispatch

jobs:
  screenshot-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        continue-on-error: true
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: NODE_ENV=production yarn build

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Europe/Moscow'
          timezoneWindows: 'Moscow Standard Time'
          timezoneMacos: 'Europe/Moscow'

      - run: yarn build:storybook --quiet

      - name: Update snapshots
        env:
          MODULE_TYPE: cjs
        run: yarn jest --config=storyshots.config.js --updateSnapshot

      - name: Push changes
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          script: |
            github.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${{ github.ref_name }}`,
              sha: "${{ github.sha }}",
            })
