name: 'npm package: publish'
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Create pull request
        id: create-pr
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "release/profi-design-system",
              base: "master",
              title: 'chore(changelog): publish profi-design-system'
            })

      - name: Add approve to pull request
        id: create_pr
        uses: actions/github-script@v4
        with:
          script: |
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: "${{steps.create-pr.outputs.result.number}}",
              comments: [{path: "", body: ""}]
            })
